runtime: nodejs
env: flex

# For testing purposes to reduce costs, it should not be used for production
# One instance, one CPU core, 0.5G RAM and 10G disk size
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10