steps:
- name: node:16.14.0
  entrypoint: npm
  args: ['run', 'install:back']
- name: node:16.14.0
  entrypoint: npm
  args: [ 'run', 'install:front' ]
- name: node:16.14.0
  entrypoint: npm
  args: ['run', 'clean']
- name: node:16.14.0
  entrypoint: npm
  args: ['run', 'build']
- name: node:16.14.0
  entrypoint: npm
  args: ['run', 'test']
timeout: 600s
queueTtl: 300s